root := justfile_directory() / "../.."
python_environment := root / ".venv"
python_interpreter := python_environment / "bin/python"
uvicorn := python_environment / "bin/uvicorn"

@run:
  echo "网页地址： http://localhost:8536/"
  echo "管理员访问： http://vfly2:123456@localhost:8536/"
  cd "{{justfile_directory()}}" && {{uvicorn}} main:app --host 0.0.0.0 --port 8536


@test: start_agent && stop_agent
  rm -rf {{justfile_directory()}}/tests/config_and_data_files
  cd "{{justfile_directory()}}" && SOURCE2RSS_CONFIG_FILE=tests/test_config.yaml {{python_interpreter}} -m pytest tests/ -m "not slow" || true

@test_all: start_agent && stop_agent
  echo "全量测试"
  cd "{{justfile_directory()}}" && SOURCE2RSS_CONFIG_FILE=tests/test_config.yaml {{python_interpreter}} -m pytest tests/ || true

@ci_test: start_agent && stop_agent
  cd "{{justfile_directory()}}" && SOURCE2RSS_CONFIG_FILE=tests/test_config.yaml {{python_interpreter}} -m pytest tests/ -m "not slow"

start_agent:
  echo "blank"

stop_agent:
  echo "blank"
