name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        shell: bash
        run: |
          bash setup4host.sh
          .env/bin/playwright install-deps
          source .env/bin/activate
          pip install -r requirements-dev.txt

      - name: Run tests
        shell: bash
        run: |
          source .env/bin/activate
          just ci_test
